---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: intranet-db
  name: intranet-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 500Mi
