---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: intranet-db
  name: intranet-db
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: nfs-storage
  storageClassName: kubevirt-csi-infra-default
  resources:
    requests:
      storage: 1Gi
