---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: intranet-db
  name: intranet-db
stringData:
  USER: appuser
  PASSWORD: securepassword
  DATABASE: quotesdb
  ROOT_PASSWORD: supersecurepassword
