---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: task-list
  name: task-list
spec:
#  schedule: "M H * * *"
  schedule: "1 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: task-list
              image: quay.io/soul/rhel9/support-tools
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
