apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  dataVolumeTemplates:
    - metadata:
        name: fedora
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  instancetype:
    name: u1.small
  preference:
    name: fedora
  runStrategy: Always
    template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks: []
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: fedora
          name: rootdisk
